name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
     -
       run: |
         false
     -
         uses: mxschmitt/action-tmate@v3
         with:
           limit-access-to-actor: true
